export const FETCH_CHATS = 'FETCH_CHATS'
export const JOIN_CHAT = 'JOIN_CHAT'
export const QUIT_CHAT = 'QUIT_CHAT'
export const CREATE_CHAT = 'CREATE_CHAT'
export const SET_ERROR='SET_ERROR'
export const SET_SOCKET="SET_SOCKET"
export const RECEIVED_MESSAGE = "RECEIVED_MESSAGE"
export const CHANGE_ACTUAL_CHAT='CHANGE_ACtUAL_CHAT'