export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SUBMIT_MESSAGE = 'SUBMIT_MESSAGE'
export const FETCH_CHATS = 'FETCH_CHATS'
export const JOIN_CHAT = 'JOIN_CHAT'
export const QUIT_CHAT = 'QUIT_CHAT'
export const CREATE_CHAT = 'CREATE_CHAT'